name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
         GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull data
          dvc remote modify --local myremote \
          gdrive_service_account_json_file_path \
          /home/nanoz-admin/runner/.cache/pydrive2fs/${{ secrets.DAGSHUB_USERNAME }}/default.json
          dvc remote modify myremote gdrive_acknowledge_abuse true
          dvc remote list
          dvc remote modify myremote gdrive_service_account_user_email \
              ihebkesraoui@gmail.com
          dvc remote modify myremote gdrive_client_id ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify myremote gdrive_client_secret ${{ secrets.DAGSHUB_TOKEN }}
          dvc pull
