name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Pull data from DVC
        run: |
          dvc remote modify --local myremote profile myprofile
          dvc remote modify --local myremote \
          gdrive_service_account_json_file_path $CACHE_HOME/pydrive2fs/${{ secrets.DAGSHUB_USERNAME }}/default.json
          dvc remote modify myremote gdrive_trash_only true
          dvc remote modify myremote gdrive_acknowledge_abuse true
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote list
          dvc remote modify myremote gdrive_service_account_user_email \
              ihebkesraoui@gmail.com
          dvc remote modify myremote gdrive_client_id ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify myremote gdrive_client_secret ${{ secrets.DAGSHUB_TOKEN }}
          dvc pull
