name: Run code

on: [push, pull_request]

jobs:
  run_code:
    name: Run code
    runs-on: ubuntu-latest
    container: khuyentran1401/customer_segmentation:dvc
    steps:
      - name: Check out the current repository
        id: checkout
        uses: actions/checkout@v2

      - name: Pull data from DVC
        run: |
          pip install dvc-gdrive
          dvc remote list
          dvc remote modify myremote gdrive_client_id ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify myremote gdrive_client_secret ${{ secrets.DAGSHUB_TOKEN }}
          dvc pull
          
