name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc3-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
         GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Install requirements
          pip install -r requirements.txt

          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull data --run-cache
          dvc remote modify --local myremote \
          gdrive_service_account_json_file_path \
          /home/nanoz-admin/runner/.cache/pydrive2fs/${{ secrets.DAGSHUB_USERNAME }}/default.json
          dvc remote modify myremote gdrive_acknowledge_abuse true
          dvc remote list
          dvc remote modify myremote gdrive_service_account_user_email \
              ihebkesraoui@gmail.com
          dvc remote modify myremote gdrive_client_id ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify myremote gdrive_client_secret ${{ secrets.DAGSHUB_TOKEN }}
          dvc pull
